apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- federation-daemonset-subprocess.yaml
- federation-daemonset-process.yaml
- federation-statefulset-subprocess.yaml
- federation-statefulset-process.yaml
- federation-multipools.yaml
